In [13]:
import numpy as np
import cv2
import paho.mqtt.client as mqttClient

In [113]:
face_cascade = cv2.CascadeClassifier('/usr/share/OpenCV/haarcascades/haarcascade_frontalface_default.xml')

def on_connect(client, userdata, flags, rc):
 
    if rc == 0:
 
        print("Connected to broker")
 
        global Connected                #Use global variable
        Connected = True                #Signal connection 
 
    else:
 
        print("Connection failed")
 
Connected = False   #global variable for the state of the connection

cap = cv2.VideoCapture(1)

broker_address= "mosquitto"
port = 1883
 
client = mqttClient.Client("Python")               #create new instance
client.on_connect= on_connect                      #attach function to callback
client.connect(broker_address, port=port)          #connect to broker


while True:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        img = cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
        #roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        byteArr = bytearray(roi_color)
        if  w != 0 and h != 0:
            #client.publish("Hello", payload="Face Found", qos=1, retain=False)
            client.publish("Faces", payload=byteArr, qos=1, retain=False)
            client.loop(2,10)
    #cv2.imshow('roi_color', roi_color)
    
        
    print(faces)
#    k = cv2.waitKey(0)
#    if k == 27:
#        break
    
cap.release()   
client.disconnect()
cv2.destroyAllWindows()
    

Connected to broker
[[162 213 127 127]]
[[160 211 134 134]]
[[165 212 129 129]]
[[161 208 139 139]]
[[166 212 130 130]]
[[166 210 133 133]]
[[167 210 135 135]]
[[169 209 133 133]]
[[170 211 131 131]]
[[169 208 137 137]]
[[170 210 134 134]]
[[172 209 135 135]]
[[172 210 133 133]]
[[172 208 136 136]]
[[177 206 132 132]]
[[178 204 137 137]]
[[184 202 137 137]]
[[184 203 139 139]]
[[189 205 133 133]]
[[188 205 136 136]]
[[191 205 134 134]]
[[194 210 129 129]]
[[196 209 133 133]]
[[200 212 127 127]]
[[204 216 126 126]]
[[206 216 129 129]]
[[211 217 131 131]]
[[214 220 126 126]]
[[217 223 122 122]]
[[220 224 122 122]]
[[219 224 124 124]]
[[217 223 131 131]]
[[218 223 129 129]]
[[217 227 126 126]]
[[215 224 128 128]]
[[215 224 132 132]]
[[218 231 121 121]]
[[213 229 128 128]]
[[214 230 122 122]]
[[217 233 119 119]]
[[216 234 117 117]]
[[218 235 119 119]]
[[217 231 122 122]]
[[217 235 117 117]]
[[215 232 121 121]]
[[215 231 119 119]]
[[215 231 121 121]]
[[218 233 116 116]]
[[216 234 116 116]]


KeyboardInterrupt: 

In [110]:
import paho.mqtt.publish as publish


publish.single("Hello", "World", hostname="mosquitto")

print("OK")

OK
